### ISSUE TITLE
Figure out replacement for neofetch

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/sbc-reviews#45]
Currently I use neofetch to grab a quick friendly-looking overview of the hardware for each system:

https://github.com/geerlingguy/sbc-reviews/blob/master/.github/ISSUE_TEMPLATE/sbc-board.md#linuxsystem-information

Neofetch is not maintained, however, so I should pick an alternative before it starts breaking on newer systems.

I like the idea of fastfetch, but it's not just an `apt install` away. I like a tool I can pop on quickly, even over SSH, and copying and pasting `wget` commands and changing version numbers for `.deb` releases is annoying.

Is there another tool that's in the Debian repos (and ideally somewhat universal, also easy to install on Ubuntu, Fedora, etc.) that replaces `neofetch`'s functionality?

**Comment by Atropa-Solanaceae** [comment]
I've since shifted to employing `screenfetch` to my systems:
https://github.com/KittyKatt/screenFetch

It has an apt repo for debian, dnf for fedora, aur for arch and so on and so forth, all listed under the install tab on their wiki:
https://github.com/KittyKatt/screenFetch/wiki/Installation

It looks pretty snazzy too! Very similar to neofetch and very customizable -- and still maintained.

**Comment by geerlingguy** [comment]
Indeed, not hard to install and use at all!

<img width="656" alt="Screenshot 2024-05-24 at 3 45 13 PM" src="https://github.com/geerlingguy/sbc-reviews/assets/481677/e8da5ada-d0af-4f1c-9df9-9e3dba7a32e6">

**Comment by geerlingguy** [comment]
There we go!
